// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwC-0-g2oDkNnQSldFOqyuffqtHqzXYP8',
    appId: '1:415849507518:web:1ac9780ece36e848bb0cef',
    messagingSenderId: '415849507518',
    projectId: 'evntly-c19',
    authDomain: 'evntly-c19.firebaseapp.com',
    storageBucket: 'evntly-c19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzjg7x4vM7Gj9aJt4vC7EZ5F1GcMSko4',
    appId: '1:415849507518:android:94c54c56c343fec8bb0cef',
    messagingSenderId: '415849507518',
    projectId: 'evntly-c19',
    storageBucket: 'evntly-c19.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfzG8H-h6Cq1573g4Ze03Ihushif60-lY',
    appId: '1:415849507518:ios:fa21ca8707b385b2bb0cef',
    messagingSenderId: '415849507518',
    projectId: 'evntly-c19',
    storageBucket: 'evntly-c19.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC19',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfzG8H-h6Cq1573g4Ze03Ihushif60-lY',
    appId: '1:415849507518:ios:fa21ca8707b385b2bb0cef',
    messagingSenderId: '415849507518',
    projectId: 'evntly-c19',
    storageBucket: 'evntly-c19.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC19',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwC-0-g2oDkNnQSldFOqyuffqtHqzXYP8',
    appId: '1:415849507518:web:03459d0582fd94e6bb0cef',
    messagingSenderId: '415849507518',
    projectId: 'evntly-c19',
    authDomain: 'evntly-c19.firebaseapp.com',
    storageBucket: 'evntly-c19.firebasestorage.app',
  );
}
